import {writeFile} from 'node:fs/promises';
const source='https://openrouter.ai/api/v1/models';
const response=await fetch(source);if(!response.ok)throw Error(`Catalog HTTP ${response.status}`);
const {data}=await response.json();if(!Array.isArray(data)||!data.length)throw Error('Empty catalog');
const models=data.filter(m=>typeof m.id==='string' && ['prompt','completion'].every(k=>m.pricing?.[k]!==undefined && m.pricing[k]!=='' && Number.isFinite(Number(m.pricing[k])) && Number(m.pricing[k])>=0)).map(m=>({id:m.id,name:m.name||m.id,pricing:m.pricing,context_length:m.context_length,top_provider:m.top_provider,architecture:m.architecture,supported_parameters:m.supported_parameters})).sort((a,b)=>a.id.localeCompare(b.id));
const snapshot={schema:'runlog.pricing-snapshot.v1',source,observed_at:new Date().toISOString(),models};
await writeFile(new URL('../pricing-snapshot.js',import.meta.url),'// Generated by scripts/refresh-prices.mjs; immutable for each package release.\nexport const PRICE_SNAPSHOT = '+JSON.stringify(snapshot,null,2)+';\n');
console.log(`Captured ${models.length} exact model IDs.`);
